on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: env1acrvpc3eu2iyyh4i.azurecr.io
        username: ${{ secrets.acr_env1acrvpc3eu2iyyh4i_username }}
        password: ${{ secrets.acr_env1acrvpc3eu2iyyh4i_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/deploy/kubernetes" -f  "deploy/kubernetes/Dockerfile" -t env1acrvpc3eu2iyyh4i.azurecr.io/env1aksvpc3eu2iyyh4i:${{ github.sha }} --label dockerfile-path=deploy/kubernetes/Dockerfile
        docker push env1acrvpc3eu2iyyh4i.azurecr.io/env1aksvpc3eu2iyyh4i:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_env1aksvpc3eu2iyyh4i_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep env1aksvpc3eu2iyyh4iafce | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace env1aksvpc3eu2iyyh4iafce`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: env1aksvpc3eu2iyyh4iafce
        container-registry-url: env1acrvpc3eu2iyyh4i.azurecr.io
        container-registry-username: ${{ secrets.acr_env1acrvpc3eu2iyyh4i_username }}
        container-registry-password: ${{ secrets.acr_env1acrvpc3eu2iyyh4i_password }}
        secret-name: env1aksvpc3edockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: deploy/kubernetes/helm-chart
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:env1acrvpc3eu2iyyh4i.azurecr.io/env1aksvpc3eu2iyyh4i
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:env1aksvpc3edockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: env1aksvpc3eu2iyyh4iafce
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          env1acrvpc3eu2iyyh4i.azurecr.io/env1aksvpc3eu2iyyh4i:${{ github.sha }}
        imagepullsecrets: |
          env1aksvpc3edockerauth
